// <auto-generated />
namespace MyCaseGuide.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ClientCase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClientCase));
        
        string IMigrationMetadata.Id
        {
            get { return "201901240638335_ClientCase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
