//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCaseGuide.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Staff
    {
        public int StaffId { get; set; }
        [Required]
        [Display(Name ="Surname")]
        public string Surname { get; set; }
        [Required,Display(Name ="Other Names")]
        public string OtherNames { get; set; }
        public string Gender { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime ModifiedOn { get; set; }
        public string Type { get; set; }
        [Display(Name ="Date of Birth")]
        [DataType(DataType.Date)]
        public DateTime DOB { get; set; }
        [Display(Name = "Date of Employment")]
        [DataType(DataType.Date)]
        public DateTime DOE { get; set; }
        public bool Status { get; set; }
        public string Address { get; set; }
        [Display(Name ="Postal Code")]
        public string PostalCode { get; set; }
        public string Town { get; set; }
        [Display(Name ="Office Number")]
        public string OfficeNo { get; set; }
        [Display(Name = "Mobile Number")]
        public string MobileNo { get; set; }
        [Display(Name ="Email Address")]
        public string EmailAddress { get; set; }
        [Display(Name ="Next of Kin")]
        public string NextOfKin { get; set; }
        public string Relationship { get; set; }
        [Display(Name ="Next of Kin Mobile No")]
        public string KTelephone { get; set; }
        [Display(Name ="Heath Insurance Number")]
        public string NHISNumber { get; set; }
        public string KRA { get; set; }
        public string Bank { get; set; }
        public string Branch { get; set; }
        [Display(Name ="Account Number")]
        public int AccountNumber { get; set; }
        [Display(Name ="Secret Code")]
        public string SecretCode { get; set; }
        public string Password { get; set; }
    }
}
